const studentList = [
  { name: 'Matt Gredler' },
  { name: 'Juliana Tyler' },
  { name: 'Veronica Blaha' },
  { name: 'Alex Bryant' },
  { name: 'Robert Duncan' },
  { name: 'Noel Hildreth' },
  { name: 'Devin Golden' },
  { name: 'Gabriel Gordon' },
  { name: 'Robert Doughty' },
  { name: 'Justin Kook' },
  { name: 'Maryam Keshavarz' },
  { name: 'Tisha Tallman' },
  { name: 'Fox Lago' },
  { name: 'Ming Tsai' },
  { name: 'Marcus Robinson' },
  { name: 'Matt Byrnes' },
  { name: 'Dishanta Kpatrick' },
  { name: 'Stone Coughlin' },
  { name: 'Banesa Guaderrama' },
  { name: 'Veronica Lee' },
  { name: 'David Ye' },
  { name: 'Tri Nguyen' },
  { name: 'Weston Dease' },
  { name: 'Raj Madisetti' },
  { name: 'Matthew Carpenter' },
  { name: 'Gina Yi' },
  { name: 'Chan Ahn' },
  { name: 'Michael Bogan' },
  { name: 'Shiobhan Fraser' },
  { name: 'Mandeep Kaur' },
  { name: 'Ben Nguyen' },
  { name: 'Marcelo Sandiford' },
  { name: 'Yoonsub Lee' },
  { name: 'Winson Mahathre' },
  { name: 'Andrew Eikhoff' },
  { name: 'Pawan Jada' },
  { name: 'Sean Hance' },
  { name: 'Christian Graves' },
  { name: 'Coulter Schrum' },
  { name: 'Alexander Dominy' },
  { name: 'Zach Miles' },
  { name: 'Kyla Middleton' },
  { name: 'Sterling Perry' }
]

module.exports = studentList;