const studentList = [
  'Matt Gredler',

  'Juliana Tyler',
  'Veronica Blaha',
  'Alex Bryant',
  'Robert Duncan',
  'Noel Hildreth',
  'Devin Golden',
  'Gabriel Gordon',
  'Robert Doughty',
  'Justin Kook',
  'Maryam Keshavarz',
  'Tisha Tallman',
  'Fox Lago',
  'Ming Tsai',
  'Marcus Robinson',
  'Matt Byrnes',
  'Dishanta Kpatrick',
  'Stone Coughlin',
  'Banesa Guaderrama',
  'Veronica Lee',
  'David Ye',
  'Tri Nguyen',
  'Weston Dease',
  'Raj Madisetti',
  'Matthew Carpenter',
  'Gina Yi',
  'Chan Ahn',
  'Michael Bogan',
  'Shiobhan Fraser',
  'Mandeep Kaur',
  'Ben Nguyen',
  'Marcelo Sandiford',
  'Yoonsub Lee',
  'Winson Mahathre',
  'Andrew Eikhoff',
  'Pawan Jada',
  'Sean Hance',
  'Christian Graves',
  'Coulter Schrum',
  'Alexander Dominy',
  'Zach Miles',
  'Kyla Middleton',
  'Sterling Perry'
]

export default studentList;